spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

sandbox.root=${user.home}/.online-java/runs
