spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
server.address=127.0.0.1

sandbox.root=${user.home}/.online-java/runs
sandbox.no-new-privileges=false
